nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-berry.cjs

@rb.bahry:registry=https://npm.pkg.github.com
registry-url: https://registry.npmjs.org/
//registry.npmjs.org/:_authToken=${process.env.auth}

